spring:
   datasource:
      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=guess_my_number_game
   jpa:
      show-sql: false
      properties:
         hibernate:
            format_sql: false
   liquibase:
      drop-first: false
      default-schema: guess_my_number_game
      change-log: classpath:/db/changelog/db.changelog-prod.yml
logging:
   level:
      root: INFO
      org.springframework:
         security: INFO
         transaction.interceptor: INFO
      org.hibernate:
         type: INFO
         stat: INFO
   file:
      path: /logs/
      name: App.log
app:
   security:
      db:
         addUsers: false