spring:
   datasource:
      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=guess_my_number_game
   jpa:
      show-sql: false
      properties:
         hibernate:
            format_sql: false
   liquibase:
      drop-first: false
      default-schema: guess_my_number_game
      change-log: classpath:/db/changelog/db.changelog-prod.yml
app:
   security:
      addAdminUser: false