spring:
   datasource:
      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=guess_my_number_game_dev
   jpa:
      show-sql: true
      properties:
         hibernate:
            format_sql: true
   liquibase:
      drop-first: true
      default-schema: guess_my_number_game_dev
      change-log: classpath:/db/changelog/db.changelog-dev.yml
app:
   security:
      addAdminUser: true
   profiling:
      restControllers: true
      services: true