server:
   port: 8080
   servlet:
      context-path: /api
      session:
         timeout: 15m
         cookie:
            same-site: Strict
            secure: true
spring:
   datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=guess_my_number_game
      username: postgres
      password: postgres
      tomcat:
         initial-size: 5
         max-wait: 20000
         max-active: 10
         min-idle: 8
         max-idle: 15
         default-auto-commit: true
   jpa:
      database-platform: org.hibernate.dialect.PostgreSQL95Dialect
      open-in-view: false
      show-sql: true
      properties:
         hibernate:
            jdbc:
               batch_size: 10
               fetch_size: 10
            max_fetch_depth: 3
            ddl-auto: none
            format_sql: true
            generate_statistics: false
            temp:
               use_jdbc_metadata_defaults: false
   liquibase:
      enabled: true
      drop-first: true
      default-schema: guess_my_number_game
      liquibase-schema: public

logging:
   level:
      root: INFO
      org.springframework:
         security: TRACE
         transaction.interceptor: TRACE
      org.hibernate:
         type: TRACE
         stat: DEBUG
   file:
      path: /logs/
      name: App.log