server:
  port: 80
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres?currentSchema=guess_number_game
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  liquibase:
    drop-first: false
    default-schema: guess_number_game
    change-log: classpath:/db/changelog/dev/changelog.yml
app:
  security:
    addAdminUser: false
    cors-origins: http://127.0.0.1:8081
  profiling:
    restControllers: false
    services: false