server:
  port: 80
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres?currentSchema=${POSTGRES_SCHEMA}
    hikari:
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: ${POSTGRES_SCHEMA}
        format_sql: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/prod/changelog.yaml
    liquibase-schema: public
    default-schema: ${POSTGRES_SCHEMA}
    drop-first: false
logging:
  config: classpath:logback-prod.xml
springdoc:
  enabled: false
  swagger-ui:
    enabled: false
app:
  security:
    addAdmin: false
    cors-origins: http://127.0.0.1:8081
  profiling:
    restControllers: false
    services: false