server:
  servlet:
    context-path: /
    session:
      timeout: 15m
      cookie:
        same-site: Strict
        secure: false
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 10000
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 60000
      max-lifetime: 180000
      auto-commit: true
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 15
          fetch_size: 90
        max_fetch_depth: 3
        generate_statistics: false
        temp:
          use_jdbc_metadata_defaults: true