server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: guess_number_game_dev
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/dev/changelog.yml
    drop-first: true
    default-schema: guess_number_game_dev
app:
  security:
    addAdminUser: true
    cors-origins: http://127.0.0.1:5500
  profiling:
    restControllers: false
    services: false