server:
  port: 80
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: guess_number_game
        format_sql: false
  liquibase:
    change-log: classpath:/db/changelog/prod/changelog.yml
    drop-first: false
    default-schema: guess_number_game
app:
  security:
    addAdminUser: false
    cors-origins: http://127.0.0.1:8081
  profiling:
    restControllers: false
    services: false