server:
  port: 80
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: guess_number_game
        format_sql: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/prod/changelog.yaml
    liquibase-schema: public
    default-schema: guess_number_game
    drop-first: false
logging:
  config: classpath:logback-prod.xml
springdoc:
  enabled: false
  swagger-ui:
    enabled: false
app:
  security:
    addAdmin: false
    cors-origins: http://127.0.0.1:8081
  profiling:
    restControllers: false
    services: false